### ISSUE TITLE
HTML Framework

### ISSUE THREAD

**Issue by stanno03** [stanno03/Fridge-Fren#3]
## Tasks:
- [x] Build index.html - Assigned to @AussieKing 
- [x] Build selectionspage.html Assigned to  @stanno03 
- [x] Build result.html - Assigned to @NatalieCampbellGit

**Comment by AussieKing** [comment]
skeleton index HTML for homepage build. will need to build remaining pages (2 & 3)
