### ISSUE TITLE
CSS - Implement Tailwind Framework

### ISSUE THREAD

**Issue by stanno03** [stanno03/Fridge-Fren#8]
## Tasks:
- [ ] Apply CSS to index.html - Assigned to @AussieKing 
- [x] Apply CSS to selectionspage.html Assigned to @stanno03 
- [x] Apply CSS to result.html - Assigned to @NatalieCampbellGit
